### ISSUE TITLE
Bug with /auc bid <amount>

### ISSUE THREAD

**Issue by DoubleDeluXe** [StarTux/CraftBay#1]
"/auc bid < amount >"  sometimes results in unwanted effects such as:
- Placing a bid higher than you typed
- Placing a bid lower than you typed

Sreenshots:

Bidding 56010 > placed bid 75050
http://imgur.com/WQ9gh

Bidding 4000 > placed bid 1005
http://imgur.com/l6IjH

**Comment by StarTux** [comment]
Not a bug. Conceptually, every participant can bid as much as they're willing to pay. They only end up paying enough to beat the minimum price as well as the next highest bid, by a configurable interval. The actual bid size is always kept hidden.
