### ISSUE TITLE
Permissions issue with 1.14.4

### ISSUE THREAD

**Issue by QuantumToasted** [StarTux/CraftBay#13]
Hello. I am not 100% certain that CraftBay is responsible for this bug I am experiencing. 

For reference, I am running Paper build `175` (1.14.4), with LuckPerms `4.4.1` for permissions, and CraftBay `2.26`. This has been attempted on my main server with several plugins and a barebones testing server with Vault/EssentialsEco and the same two versions of LuckPerms and CraftBay.

When a user with permission node `auction.start` attempts to start an auction, they get the following generic Bukkit error message:
```
I'm sorry, but you do not have permission to perform this command.
Please contact the server administrators if you believe that this is in error.
```
I haven't tested the full extent of what permission nodes are bugging out, but I know that users at the very least are unable to start auctions even with the correct permission node set. Normally if the user didn't have permission they would get the LuckPerms `You do not have permission to use this command.` message, but instead they seem to be getting the one which I believe is shown when a command that requires being a server operator is used by a normal user?

Making them server operators or giving them `auction.*` seems to fix the problem, but that is obviously not what I would like to do for users to be able to use this plugin.

Enabling debug mode in config.yml does not show anything at all, as well.

**Comment by StarTux** [comment]
Hello,

in order to use the command itself, the `auction.info` permission is required. `auction.start` is then required to start an auction with one of the subcommands.
